name: Demo-credit CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.RESIHUB_AWS }}
          port: ${{ secrets.AWS_PORT }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo -i bash -c '
            cd /var/www/prod-resihub && \
            git pull origin main && \
            npm install && \
            npm run build && \
            npm run db-push --skip-generate --accept-data-loss && \
            pm2 reload api && \
            pm2 reload socket && \
            pm2 reload queue && \
            pm2 save
            '
